name: Go Build Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        # base
        apt update --yes && apt upgrade --yes
        apt install --yes \
            build-essential \
            locales \
            fakeroot \
            devscripts \
            libxtst-dev \
            libgtk2.0-dev \
            libgtk-3-dev \
            libanthy-dev \
            libchewing3-dev \
            libappindicator-dev \
            libappindicator3-dev \
            qtbase5-private-dev

    -run: echo 'en_US.UTF-8 UTF-8' >/etc/locale.gen && locale-gen

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v -ldflags -H=windowsgui -o build/grif.exe ./grif.go
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.RELEASE_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          go.exe
